imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  webo_deliverytime.hook.display_delivery_time:
    class: WeboDeliveryTime\Hook\DisplayDeliveryTime
    public: true
    parent: 'webo_delivery_time.hook.abstract_hook'
    arguments:
      - '@webo_delivery_time.presenter.delivery_time_shipping_presenter'